name: CI/CD Pipline for Java application
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: '17'
  DOCKER_IMAGE: '${{ secrets.DOCKER_USERNAME }}/book-library-api'

jobs:
  # Build and Test with Junit
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #SonarCloud needs the full history
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Compile Project
        run: mvn -B compile
      - name: Run Tests (Junit + mockito)
        run: mvn -B test
      - name: Generate Code Coverage Report
        run: mvn -B jacoco:report
      - name: Upload Test Results
        if: always() # Ensure this step runs even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/surefire-reports/
            target/site/jacoco
          retention-days: 5